language: python
python:
  - "3.6"
  - "3.5"
# command to install dependencies
install:
  - pip install pytest pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=python-data-structures/
after_success:
  coveralls
